### ISSUE TITLE
Automatische Updates wegen fehlender Sortierung

### ISSUE THREAD

**Issue by srenatus** [okfde/odmonitormap#11]
Hallo!

Beim umschauen in diesem interessanten Projekt (:+1:) fällt auf, dass die meisten (?) automatischen Updates nur eine andere Reihenfolge der Zeilen beinhalten. Mit [order by](http://en.wikipedia.org/wiki/Order_by) in der SQL-Query könnte man dem entgegenwirken (z.B.). &lt;/nitpick>

Viele Grüße
Stephan

**Comment by mattfullerton** [comment]
Habe jetzt erst den Kommentar gesehen. Danke für das Nitpicking. Wir werden bald diese Infrastruktur sowieso einstellen.

**Comment by srenatus** [comment]
Achso, na dann ;)
